import type { Metadata } from 'next';
import './globals.css';
import { Karla } from 'next/font/google';
import { Toaster } from 'sonner';
import Providers from '@/components/providers';

const karla = Karla({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <Toaster />
      <body
        className={`${karla.className} antialiased dark:text-gray-50 dark:bg-black text-black bg-white`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
