import type { Metadata } from 'next';
import './globals.css';
import { Karla } from 'next/font/google';
import { Toaster } from 'sonner';

const karla = Karla({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Toaster richColors />
      <body className={`${karla.className} antialiased`}>{children}</body>
    </html>
  );
}
